### ISSUE TITLE
Metadata category API returns a non-json object

### ISSUE THREAD

**Issue by wasade** [biocore/microsetta-public-api#24]
The summary output for `age_cat` in Swagger reports as:

```bash
can't parse JSON.  Raw result:

[
  "teen", 
  "60s", 
  "Not provided", 
  "child", 
  "30s", 
  "50s", 
  "40s", 
  NaN, 
  "20s", 
  "70+", 
  "baby"
]
```

What I suspect is the object needs to come back as something like

```bash
{'category-values': [
  "teen", 
  "60s", 
  "Not provided", 
  "child", 
  "30s", 
  "50s", 
  "40s", 
  NaN, 
  "20s", 
  "70+", 
  "baby"
]}
```

...or something like that

**Comment by gwarmstrong** [comment]
AFAIK (see [RFC 8259](https://tools.ietf.org/html/rfc8259)) an array by itself (not nested inside an object) is valid JSON.

The issue I see above is that there is a NaN value. See #21 . Merging that PR should fix your issue ^_^

**Comment by wasade** [comment]
Ah good call, merged :)
